### ISSUE TITLE
Recommend barcoderdev's FBX2glTF

### ISSUE THREAD

**Issue by Heus-Sueh** [V-Sekai/unidot_importer#19]
> To install, one must download FBX2glTF from https://github.com/revolufire/FBX2glTF/releases/, then rename to FBX2glTF.exe and move it into this addon directory.

the reason for recommending this version is because it is more compatible and is being actively maintained by barcoderdev
https://github.com/barcoderdev/FBX2glTF

**Comment by Moonwolf287** [comment]
Actually I found that if you take one from the github actions instead of a release file it is just as reliable and also still maintained.
barcoderdevs version mainly runs better because it is forked from a later version than the last release was built.

**Comment by Heus-Sueh** [comment]
> Actually I found that if you take one from the github actions instead of a release file it is just as reliable and also still maintained. barcoderdevs version mainly runs better because it is forked from a later version than the last release was built.

interesting :thinking:

**Comment by fire** [comment]
@lyuma Probably time for a new fbx2gltf release

**Comment by akien-mga** [comment]
> Actually I found that if you take one from the github actions instead of a release file it is just as reliable and also still maintained. barcoderdevs version mainly runs better because it is forked from a later version than the last release was built.

That's surprising because the last release on https://github.com/godotengine/FBX2glTF at the time of your comment was `v0.13.0`, and there was no further code change in the `master` branch, nor changes in barcodedev's fork that would impact the behavior of FBX2glTF. So I suspect you might have been using an older version if you found that the GH artifacts performed better.

We now released `v0.13.1` with an additional bugfix: https://github.com/godotengine/FBX2glTF/releases/tag/v0.13.1

**Comment by lyuma** [comment]
Godot has released a new version of FBX2glTF with the preserve skeleton fix (for mixamo animations). Thanks @akien-mga! My technical understanding is it shouldn't have any effect on content being imported into Godot compared to the last install.

I've been through the code changes I just don't see how barcoderdev's version has any effect compared to the current or previous godotengine release, in terms of how Unidot uses it.

So my assumption right now is Unidot doesn't check very carefully if FBX2glTF is properly installed, and I bet either people didn't install it correctly, or they did but used Facebook's outdated version with lots of bugs.

The action item I'll pursue is to require FBX2glTF to be present in the project, and validate its version before permitting import from Unidot (maybe a "I know what I'm doing" override if you really don't want to use the recommended versions). And also display the version number so if something does go wrong, we know what.

That, and I'm going to finish the debug logging system so it logs errors per-asset into a logfile, rather than stdout. And then you can browse the specific errors from each asset as part of debugging.

I'll keep this open for now, because there is some issue here, since Gamefromscratch ran into something, as did users here. It's just not clear to me exactly what they hit.

**Comment by fire** [comment]
If there's nothing changed substantially in barcoderdevs's version, we can't recommend it.

See also my comments earlier https://github.com/V-Sekai/unidot_importer/issues/19#issuecomment-1586360307

**Comment by Heus-Sueh** [comment]
> If there's nothing changed substantially in barcoderdevs's version, we can't recommend it.
> 
> See also my comments earlier https://github.com/V-Sekai/unidot_importer/issues/19#issuecomment-1586360307

ok
