### ISSUE TITLE
Godot Crashes Importing Specific Package Files containing NaN vertices

### ISSUE THREAD

**Issue by TheDarkBadger** [V-Sekai/unidot_importer#20]
I've been importing some asset packs from a recent Humble Bundle. Some of the packages import with no issues, however some cause Godot to crash during the import process. The import runs for a few seconds and then Godot closes.
Reopening Godot will cause it to crash again, the only way to get back into the project is to remove the files created for the package in the Assets folder.

I thought this might be from the amount of logs that are generated but i am still having the same issues after removing the print statements in Unidot.

I've been unable to figure out why its happening with specific packages, as im finding it hard to debug the addon as you can not use breakpoints in Godot Editor Addons (afaik)

Link to packages (I can provide if needed):
 - https://assetstore.unity.com/packages/3d/props/poly-lite-survival-collection-220452#description
 - https://assetstore.unity.com/packages/3d/props/weapons/poly-mega-weapons-kit-215666

**Comment by lyuma** [comment]
The crash happens in the `SM_Special_Submachine_Gun_Clean` mesh within the converted `SM_Special_Submachine_Gun_Clean.gltf` mesh. This seems to be the only model with the issue in the free package. I did not test the paid package, but considering it is by the same author and contains weapons, it might be an issue with the same file.

You can see here that some vertices are NaN. This appears to be propagating into integer values in the LOD generation code, causing negative and out of range ints.
![image showing nan values present in the glTF converted file](https://github.com/V-Sekai/unidot_importer/assets/39946030/864b39f9-a606-439e-bb03-70a4f5737f85)

To rule out a bug in FBX2glTF, I went back to the original .fbx, converted it to ASCII using the official Autodesk FBX Converter 
2013 tool, and verified that indeed the NaN (printed as `-1.#IND` ) is present in the original FBX file.
![image showing NaN present in the original fbx](https://github.com/V-Sekai/unidot_importer/assets/39946030/72dc77e3-f912-4643-a717-f4847bfcf7db)
Disabling mesh LOD may workaround the crash.

In the `Poly Light Survival Collection` asset package, I avoided the problem by unchecking the `SM_Special_Submachine_Gun_Clean` fbx and prefab files. Apparently this model isn't so clean, as we can see. After doing this, it achieves a successful import of at least some of the content:
![most assets green, submachine unchecked](https://github.com/V-Sekai/unidot_importer/assets/39946030/66e6a3f7-c680-4e2a-b5f0-41f5e8eda97a)
![image showing some assets imported](https://github.com/V-Sekai/unidot_importer/assets/39946030/3440f08a-144b-4c5f-a6cf-5e4afb99352a)

In terms of work for Godot, it would be good for Godot not to crash when encountering a NaN in an imprted FBX or glTF file. The saying goes that if something *can* happen, it *will* happen. As you have proven, such files *do* exist in the wild, and Godot should do better to handle this.

I do not believe that there is anything reasonable I can do from within Unidot to prevent this crash: I may attempt to make a clean fbx or gltf file with a nan in it to reproduce the issue, and then file an issue upstream on Godot.
Perhaps it can log the file currently being imported, but this is not easy since this is handled by the engine itself.

**Comment by lyuma** [comment]
It was not so easy: I had a debugger attached, and when it crashes I went up in the stack and printed the path variable

If you want a temporary workaround, open unity_asset_adapter.gd and find the line that adds
"meshes/create_shadow_meshes", false
And duplicate the line and put "meshes/generate_lods", false

To disable LOD generation on new imports. (You'll have to clear out the bad assets first to stop it from crashing)
