### ISSUE TITLE
Converted meshes have offset origins

### ISSUE THREAD

**Issue by TylerKostuch** [V-Sekai/unidot_importer#48]
When importing a unity package, each prefab that contains multiple meshes has each sub mesh offset. (See photo below)

![image](https://github.com/barcoderdev/unitypackage_godot/assets/32139518/3705b3d5-a603-40ff-b82d-8b1c5d92f4dd)

## Additional Information

- I've tried converting multiple unitypackages, the picture comes from a Synty package.
- I'm using [this build](https://github.com/godotengine/FBX2glTF/actions/runs/8407445874) of FBX2glTF but also tried the official release from June 2023.
- v4.2.stable.mono.official [46dc27791]
- Windows 10

Please let me know if anyone has any ideas or needs more information. I searched quite extensively before posting here, so apologies if this is a resolved issue somewhere.

**Comment by lyuma** [comment]
Hi Tyler,
Thanks for the report!
Indeed, I am aware of some cases in which FBX files which used the RotationPivot feature of the FBX format have an incorrect mesh origin, which then causes Unidot to place the mesh incorrectly. This is due to a deficiency in FBX2glTF, so it is not something that will be fixed on Godot 4.2 and earlier.

That said, the latest version of Godot 4.3 dev contains support for a brand-new fbx importer, ufbx, and we worked with the developers to ensure pivots are correctly imported. I believe if you try the latest version of Unidot on a 4.3 dev build, you should be pleased with the results in terms of mesh origin. (note that I've been seeing some regressions with material slot ordering: 4.3 is still pre-beta, so expect bugs of course)

**Comment by TylerKostuch** [comment]
This is awesome news, I'll use 4.3 and report back.

I figured it was something going on with FBX2glTF which is why I tried different builds of it.

**Comment by TylerKostuch** [comment]
Sadly, using v4.3.dev1.mono.official [9d1cbab1c], I'm still seeing the same result. :(

**Comment by lyuma** [comment]
4.3dev1 is from last year, too old. Iam not sure a reent enough dev build exists?

**Comment by TylerKostuch** [comment]
Yep, I used dev5 and it worked great!
https://godotengine.org/download/archive/4.3-dev5/

![image](https://github.com/V-Sekai/unidot_importer/assets/32139518/a306b334-3c54-429f-a58a-42100292b093)
